-- ============================================================
--  MISE À JOUR · Likes & commentaires PARTAGÉS (visibles par tous)
--  À exécuter UNE FOIS dans Supabase : SQL Editor > New query > coller > Run.
--
--  · Avant, les likes/commentaires étaient stockés dans le navigateur de
--    chaque visiteur (donc pas partagés, et ils disparaissaient).
--  · Maintenant ils sont enregistrés dans la base : tout le monde voit les
--    mêmes likes et commentaires, en permanence.
--  · Le même système sert pour les photos/vidéos ET pour les histoires
--    (media_id = "histoire-<id>").
--  · Tout le monde peut LIRE ; un fan connecté ajoute/retire SES propres
--    likes et commentaires.
-- ============================================================

-- ---- LIKES : un like = une ligne (un seul par fan et par contenu) ----
create table if not exists media_likes (
  media_id text,
  user_id  uuid references auth.users(id),
  cree_le  timestamptz default now(),
  primary key (media_id, user_id)
);

alter table media_likes enable row level security;

drop policy if exists ml_lecture   on media_likes;
drop policy if exists ml_insertion on media_likes;
drop policy if exists ml_suppr     on media_likes;

-- Tout le monde peut lire (pour compter les likes)
create policy ml_lecture on media_likes
  for select using (true);
-- Un fan connecté aime pour lui-même
create policy ml_insertion on media_likes
  for insert to authenticated with check (auth.uid() = user_id);
-- Un fan connecté peut retirer SON like
create policy ml_suppr on media_likes
  for delete to authenticated using (auth.uid() = user_id);


-- ---- COMMENTAIRES ----
create table if not exists media_commentaires (
  id       bigint generated by default as identity primary key,
  media_id text,
  user_id  uuid references auth.users(id),
  pseudo   text,
  texte    text,
  cree_le  timestamptz default now()
);

alter table media_commentaires enable row level security;

drop policy if exists mc_lecture   on media_commentaires;
drop policy if exists mc_insertion on media_commentaires;
drop policy if exists mc_suppr     on media_commentaires;
drop policy if exists mc_admin_maj on media_commentaires;

-- Tout le monde peut lire les commentaires
create policy mc_lecture on media_commentaires
  for select using (true);
-- Un fan connecté écrit un commentaire en son nom
create policy mc_insertion on media_commentaires
  for insert to authenticated with check (auth.uid() = user_id);
-- Un fan connecté peut supprimer SON commentaire
create policy mc_suppr on media_commentaires
  for delete to authenticated using (auth.uid() = user_id);
-- La modératrice peut supprimer n'importe quel commentaire (modération)
create policy mc_admin_maj on media_commentaires
  for delete to authenticated
  using ((auth.jwt() ->> 'email') = 'elisabeth.sikora@orange.fr');

-- ✅ Terminé.
