-- ============================================================
--  MISE À JOUR · Photos / vidéos des fans (avec modération)
--  À exécuter UNE FOIS dans Supabase : SQL Editor > New query > coller > Run.
--
--  · Les fans envoient photos / dessins / selfies / vidéos → en attente.
--  · TOI (elisabeth.sikora@orange.fr) tu vois tout et tu valides.
--  · Une fois validées, elles sont visibles par tous.
-- ============================================================

create table if not exists medias (
  id       bigint generated by default as identity primary key,
  user_id  uuid references auth.users(id),
  fan_id   text,                         -- l'id de la fiche fan (pour points/badges)
  pseudo   text,
  type     text,                         -- 'photo' | 'dessin' | 'selfie' | 'video'
  contenu  text,                         -- image en base64 (photo/dessin/selfie)
  lien     text,                         -- URL (pour une vidéo)
  legende  text,
  concert  text,
  valide   boolean default false,
  rejete   boolean default false,
  cree_le  timestamptz default now()
);

alter table medias enable row level security;

drop policy if exists medias_lecture      on medias;
drop policy if exists medias_lecture_soi  on medias;
drop policy if exists medias_insertion    on medias;
drop policy if exists medias_admin_read   on medias;
drop policy if exists medias_admin_maj    on medias;

-- lecture publique de ce qui est validé
create policy medias_lecture on medias
  for select using (valide = true);

-- un fan connecté voit ses propres envois (même en attente)
create policy medias_lecture_soi on medias
  for select to authenticated using (auth.uid() = user_id);

-- un fan connecté envoie SES médias (non validés au départ)
create policy medias_insertion on medias
  for insert to authenticated
  with check (auth.uid() = user_id and valide = false);

-- LA MODÉRATRICE (toi) voit tout et peut valider/rejeter
create policy medias_admin_read on medias
  for select to authenticated
  using ((auth.jwt() ->> 'email') = 'elisabeth.sikora@orange.fr');

create policy medias_admin_maj on medias
  for update to authenticated
  using ((auth.jwt() ->> 'email') = 'elisabeth.sikora@orange.fr')
  with check (true);

-- ✅ Terminé.
