-- ============================================================
--  TOUT CE QUI EST EN ATTENTE · à coller UNE FOIS dans Supabase
--  SQL Editor > New query > tout coller > Run.  (100% sans risque :
--  "if not exists" ignore ce qui existe déjà, rien n'est supprimé.)
-- ============================================================

-- 1) Colonnes de la fiche : "fan depuis", position exacte, nb de projets
alter table fans add column if not exists fan_depuis text;
alter table fans add column if not exists lat double precision;
alter table fans add column if not exists lon double precision;
alter table fans add column if not exists projets_organises int default 0;

-- 2) LIKES partagés (visibles par tous)
create table if not exists media_likes (
  media_id text,
  user_id  uuid references auth.users(id),
  cree_le  timestamptz default now(),
  primary key (media_id, user_id)
);
alter table media_likes enable row level security;
drop policy if exists ml_lecture   on media_likes;
drop policy if exists ml_insertion on media_likes;
drop policy if exists ml_suppr     on media_likes;
create policy ml_lecture   on media_likes for select using (true);
create policy ml_insertion on media_likes for insert to authenticated with check (auth.uid() = user_id);
create policy ml_suppr     on media_likes for delete to authenticated using (auth.uid() = user_id);

-- 3) COMMENTAIRES partagés (avec réponses)
create table if not exists media_commentaires (
  id        bigint generated by default as identity primary key,
  media_id  text,
  user_id   uuid references auth.users(id),
  pseudo    text,
  texte     text,
  parent_id bigint,
  cree_le   timestamptz default now()
);
alter table media_commentaires add column if not exists parent_id bigint;
alter table media_commentaires enable row level security;
drop policy if exists mc_lecture   on media_commentaires;
drop policy if exists mc_insertion on media_commentaires;
drop policy if exists mc_suppr     on media_commentaires;
drop policy if exists mc_admin_maj on media_commentaires;
create policy mc_lecture   on media_commentaires for select using (true);
create policy mc_insertion on media_commentaires for insert to authenticated with check (auth.uid() = user_id);
create policy mc_suppr     on media_commentaires for delete to authenticated using (auth.uid() = user_id);
create policy mc_admin_maj on media_commentaires for delete to authenticated using ((auth.jwt() ->> 'email') = 'elisabeth.sikora@orange.fr');

-- ✅ Terminé. Tu peux tout pousser dans GitHub ensuite.
